
all:timeclient.o timeserver.o shub.o


timeclient.out:timeclient.c
	gcc timeclient.c -o timeclient.out
	
timeserver.out:timeserver.c
	gcc timeserver.c -o timeserver.out
	
shub.o:shub.c
	gcc shub.c -o shub.o
